config/routes.rb
Rails.application.routes.draw do

  devise_for :restaurants
  root 'application#index'
  get '/signup' => 'sign_up#new'
  post '/create_restaurant' => 'sign_up#create'

  scope :api, defaults: {format: :json} do
    post '/send_text/:id' => 'send_text#send_text_message'
    resources :parties
    get '/parties/destroy/all'  => 'parties#destroy_all'
  end

end

app/models/party.rb
class Party < ActiveRecord::Base
	belongs_to :restaurant

	def self.create_new_instance(data)
	end


end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable

	has_many :parties

  def self.email_is_unique(email)
    where(email: email).count == 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_restaurant!

  def index
  end
  
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
	respond_to :html, :json, :xml

  def index
  	@parties = current_restaurant.parties
  	respond_with(@parties)
  end

  def create
		@party = Party.create(name: params[:name], party_count: params[:size], phone: params[:phone], restaurant_id: current_restaurant.id)
  	respond_with(@party)
  end

  def destroy
  	@party = Party.find(params[:id])
  	@party.destroy
  	render :json => 'Success'
  end

  def destroy_all
  	Party.destroy_all(:restaurant_id => current_restaurant.id)
  	render :json => 'Success'
  end

end

app/controllers/send_text_controller.rb
class SendTextController < ApplicationController
  def index
  end
 
  def send_text_message
    @party = Party.find(params[:id])
    @restaurant = @party.restaurant
    number_to_send_to = @party.phone
 
    twilio_sid = 'AC1212dc49b7f4955e9493cd368748f650' #Rails.application.secrets.twilio_account_sid #ENV['twilio_sid']
    twilio_token = '92993d5fec98ed662deb0bcb605ebbea'#Rails.application.secrets.twilio_auth_token #ENV['twilio_auth_token']
    twilio_phone_number = "3317033062"

    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
  
    @twilio_client.account.sms.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => number_to_send_to,
      :body => "This is an automated message from #{@restaurant.name.capitalize}. Your table is now ready."
    )
    render :json => 'Success'
  end
end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController
	skip_before_filter :authenticate_restaurant!

  def new
		@restaurant = Restaurant.new
  end

  def create
  	@restaurant = Restaurant.new(restaurant_params)

    if unique_email(params[:restaurant][:email]) && matching_password(params[:restaurant]) #no_form_errors(params[:restaurant])
      @restaurant.save
      sign_in @restaurant
      redirect_to root_path
    elsif !unique_email(params[:restaurant][:email])
      redirect_to signup_path, alert: "That email has already been taken, please select a unique email."
    elsif !matching_password(params[:restaurant])
      redirect_to signup_path, alert: "Please make sure your passwords are matching."
  	end

  end

  private

  def unique_email(email)
    Restaurant.email_is_unique(email)
  end

  def matching_password(params)
    params[:password] == params[:password_confirmation]
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/application/index.html.erb
<div class='full-height' ng-view=""></div>

app/views/layouts/_navbar.html.erb
<div class='contain-to-grid nav-bar-div'>
  <nav class='top-bar' data-topbar>
    <ul class='title-area fore-front'>
      <li class='name'>
        <h1>
          <a href="/#">WaitList</a>
        </h1>
      </li>
      <li class='toggle-topbar menu-icon'>
        <a href="#">Menu</a>
      </li>
    </ul>
    <% if restaurant_signed_in? %>
      <section class='top-bar-section'>
          <ul class='right'>
            <li class='has-dropdown'><a ui-sref="#"><%= current_restaurant.name %></a>
              <ul class='dropdown'>
                <li class='divider'></li>
                <li>
                  <%= link_to "Sign out", destroy_restaurant_session_path, :method => :delete %>
                </li>
                <li class='divider'></li>
              </ul>
            </li>
          </ul>
      </section>
    <% end %>


    

  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "WaitList" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>


  <body ng-app="AngularRails">
  	<div class='wholeapp'>
	  	<%= render partial: "layouts/navbar" %>
	  	<div class='row anti-nav-bar'>
	  		<div class='small-12 columns full-height'>
            <!-- # <p class="notice"><%= notice %></p> -->
            <p class="alert"><%= alert %></p>
	    		<%= yield %>
	    	</div>
	    </div>
	    <%= javascript_include_tag "application" %>
    </div>
  </body>
</html>

app/views/sign_up/new.html.erb
<h2>Sign up</h2>
<%= form_for( @restaurant, url: create_restaurant_path(@restaurant)) do |f| %>
	
	<div><%= f.label 'Name of Restaurant' %><br />
  <%= f.text_field :name, autofocus: true %></div>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, autofocus: true %></div>

  <div><%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %></div>

  <div><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %></div>

  <div><%= f.submit "Sign up", {class: 'button'}%></div>
<% end %>